import { IServerDomainKeyValue } from '@module/recovery/application/interface/server-domain-key-value.interface';
import { ApiProperty } from '@nestjs/swagger';
import { IsObject } from 'class-validator';

export class GenerateRecoveryChallengeResponseDto {
  @ApiProperty({
    description: 'Challenges generated by server for authentication with SEP10',
    example: {
      challenges: {
        'Recovery-1-Domain': 'challenge-1',
        'Recovery-2-Domain': 'challenge-2',
      },
    },
    type: Object,
  })
  @IsObject()
  challenges: IServerDomainKeyValue;
}
