import { IServerDomainKeyValue } from '@module/recovery/application/interface/server-domain-key-value.interface';
import { ApiProperty } from '@nestjs/swagger';
import { IsObject } from 'class-validator';

export class GenerateRecoveryTokenResponseDto {
  @ApiProperty({
    description: 'An object containing the tokens generated by the servers',
    example: {
      tokens: {
        'Recovery-1-Domain': 'token-1',
        'Recovery-2-Domain': 'token-2',
      },
    },
    type: Object,
  })
  @IsObject()
  tokens: IServerDomainKeyValue;
}
