version: '3'

services:
  db:
    image: postgres:latest
    cap_add:
      - SYS_NICE
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/postgresql/:/var/lib/postgresql
  cognito:
    image: jagregory/cognito-local
    ports:
      - '${COGNITO_PORT:-9229}:9229'
    volumes:
      - ./data/docker/volumes/cognito:/app/.cognito
